apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-gateway-fabric
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-gateway
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://helm.nginx.com/stable
    chart: nginx-gateway-fabric
    targetRevision: 2.1.0
    helm:
      releaseName: ngf
      values: |
        nginx:
          service:
            type: NodePort
