apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Charansai8127/Iac'
    path: vault
    targetRevision: main
    helm:
      values: |
        server:
          ha:
            enabled: true
            replicas: 3
          raft:
            enabled: true
            setNodeId: true
          dataStorage:
            enabled: true
            size: 2Gi
            storageClass: vault-storage
          config: |
            ui = true
            cluster_name = "vault-integrated-storage"

            listener "tcp" {
              address = "[::]:8200"
              cluster_address = "[::]:8201"
              tls_disable = true
            }

            storage "raft" {
              path = "/vault/data"
              retry_join { leader_api_addr = "http://vault-0.vault-internal:8200" }
              retry_join { leader_api_addr = "http://vault-1.vault-internal:8200" }
              retry_join { leader_api_addr = "http://vault-2.vault-internal:8200" }
            }
        injector:
          enabled: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: vault
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
