apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.releases.hashicorp.com
    chart: vault
    targetRevision: 0.28.0
    helm:
      values: |
        server:
          ha:
            enabled: true
            replicas: 3
            raft:
              enabled: true
              setNodeId: true
              config: |
                storage "raft" {
                  path    = "/vault/data"
                  retry_join {
                    leader_api_addr = "http://vault-0.vault-internal:8200"
                  }
                  retry_join {
                    leader_api_addr = "http://vault-1.vault-internal:8200"
                  }
                  retry_join {
                    leader_api_addr = "http://vault-2.vault-internal:8200"
                  }
                }
                listener "tcp" {
                  address     = "[::]:8200"
                  cluster_address = "[::]:8201"
                  tls_disable = "true"
                }
                ui = true
          dataStorage:
            enabled: true
            size: 2Gi
            storageClass: vault-storage
          service:
            type: ClusterIP
          extraVolumes:
            - name: vault-logs
              persistentVolumeClaim:
                claimName: vault-logs-pvc
          extraVolumeMounts:
            - name: vault-logs
              mountPath: /vault/logs
        injector:
          enabled: true
        ui:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-logs-pvc
  namespace: vault
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: vault-storage
