{
  "server": {
    "ha": {
      "enabled": true,
      "replicas": 3
    },
    "raft": {
      "enabled": true,
      "setNodeId": true
    },
    "dataStorage": {
      "enabled": true,
      "size": "2Gi",
      "storageClass": "vault-storage"
    },
    "config": "ui = true\ncluster_name = \"vault-integrated-storage\"\n\nlistener \"tcp\" {\n  address = \"[::]:8200\"\n  cluster_address = \"[::]:8201\"\n  tls_disable = true\n}\n\nstorage \"raft\" {\n  path = \"/vault/data\"\n  retry_join { leader_api_addr = \"http://vault-0.vault-internal:8200\" }\n  retry_join { leader_api_addr = \"http://vault-1.vault-internal:8200\" }\n  retry_join { leader_api_addr = \"http://vault-2.vault-internal:8200\" }\n}"
  },
  "injector": {
    "enabled": true
  }
}
