server:
  ha:
    enabled: true
    replicas: 3
    raft:
      enabled: true
      setNodeId: true
  listener:
    tcp:
      address: "[::]:8200"
      clusterAddress: "[::]:8201"
      tlsDisable: true
  storage:
    raft:
      path: "/vault/data"
      retryJoin:
        - leaderApiAddr: "http://vault-0.vault-internal:8200"
        - leaderApiAddr: "http://vault-1.vault-internal:8200"
        - leaderApiAddr: "http://vault-2.vault-internal:8200"
  ui:
    enabled: true
  dataStorage:
    enabled: true
    size: 2Gi
    storageClass: vault-storage
  service:
    type: ClusterIP
  extraVolumes:
    - name: vault-logs
      persistentVolumeClaim:
        claimName: "vault-logs-pvc"
  extraVolumeMounts:
    - name: vault-logs
      mountPath: /vault/logs

injector:
  enabled: true
