apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: v1.14.3
    helm:
      values: |
        installCRDs: true
        # Optional: configure leader election namespace, webhook settings, etc.
        # webhook:
        #   failurePolicy: Ignore
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-gateway
  syncPolicy:
    automated:
      selfHeal: true
      prune: false
